<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Grouped product data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\BaseImage
 * @var $block \Magento\GroupedProduct\Block\Product\View\Type\Grouped
 */
?>
<?php $block->setPreconfiguredValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $_associatedProducts = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>
<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>

<?php
$filters = "";
$_levels = $_product->getResource()->getAttribute("level_1");
if ($_levels){
    $filters = $_levels->getFrontend()->getValue($_product);
}
$_levels = $_product->getResource()->getAttribute("level_2");
if ($_levels){
    $filters .= ", ".$_levels->getFrontend()->getValue($_product);
}

$filters = explode(", ", $filters);
echo "<ul class='filters'>";
echo "<li><label><input type='radio' name='pFilter' class='action primary' onclick='filterAssociateProducts(event)' checked='checked' value='*'><span>All</span></label></li>";
foreach ($filters as $filter){
  if(!empty($filter)){
    echo "<li><label><input type='radio' name='pFilter' class='action primary' onclick='filterAssociateProducts(event)' value='".$filter."'><span>".$filter."</span></label></li>";
  }
}
echo "</ul>";
?>

<div id="validation-message-box" class="fix-bottom-error"></div>
<div class="table-wrapper grouped">
    <table class="table data grouped" id="super-product-table" width="100%">
        <caption class="table-caption"><?= /* @escapeNotVerified */ __('Grouped product items') ?></caption>
        <thead>
        <tr>
            <th class="col item hide" scope="col"></th>
            <th class="col item" scope="col"></th>
            <?php if ($_product->isSaleable()): ?>
                <th class="col qty" scope="col"><span class="qty-label"><?= /* @escapeNotVerified */ __('Qty') ?></span></th>
            <?php endif; ?>
        </tr>
        </thead>
        <tbody>
        <?php if ($_hasAssociatedProducts): ?>
        <?php foreach ($_associatedProducts as $_item): ?>
            <tr>
                <td class="hide">
                  <div><?php
                    $item = $objectManager->get('Magento\Catalog\Model\Product')->load($_item->getId());
                    $_levels = $item->getResource()->getAttribute("level_1");
                    if ($_levels){
                        echo $_levels->getFrontend()->getValue($item);
                    }
                    $_levels = $item->getResource()->getAttribute("level_2");
                    if ($_levels){
                        echo ", ".$_levels->getFrontend()->getValue($item);
                    }
                  ?></div>
                </td>
                <td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col item">
                    <h4 class="product-item-name"><?= $block->escapeHtml($_item->getName()) ?></h4>
                    <?php if ($block->getCanShowProductPrice($_product)): ?>
                        <?php if ($block->getCanShowProductPrice($_item)): ?>
                            <?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>
                        <?php endif; ?>
                     <?php endif; ?>
                </td>
                <?php if ($_product->isSaleable()): ?>
                <td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="col qty">
                <?php if ($_item->isSaleable()) : ?>
                    <div class="control qty">
                        <input type="number"
                               name="super_group[<?= /* @escapeNotVerified */ $_item->getId() ?>]"
                               data-selector="super_group[<?= /* @escapeNotVerified */ $_item->getId() ?>]"
                               value="<?= /* @escapeNotVerified */ $_item->getQty() * 1 ?>"
                               title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                               class="input-text qty"
                               data-validate="{'validate-grouped-qty':'#super-product-table'}"
                               data-errors-message-box="#validation-message-box"/>
                    </div>
                <?php else: ?>
                    <div class="stock unavailable" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
                        <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
                    </div>
                <?php endif; ?>
                </td>
                <?php endif; ?>
            </tr>
            <?php if ($block->getCanShowProductPrice($_product)
                && $block->getCanShowProductPrice($_item)
                && trim($block->getProductPriceHtml(
                    $_item,
                    \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                ))): ?>
                <tr class="row-tier-price">
                    <td colspan="2">
                        <?= $block->getProductPriceHtml(
                            $_item,
                            \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                        ) ?>
                    </td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td class="unavailable"
                    colspan="<?php if ($_product->isSaleable()): ?>4<?php else : ?>3<?php endif; ?>">
                    <?= /* @escapeNotVerified */ __('No options of this product are available.') ?>
                </td>
            </tr>
        <?php endif; ?>
      </tbody>
    </table>
</div>
