<?php
// @codingStandardsIgnoreFile
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed" id="detailsModal" style="display:none;">
        <?php $layout = $block->getLayout(); ?>
        <div>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                    switch ($name) {
                      case 'product.info.description':
                      ?>
                      <div class="descriptions">
                          <?php /* @escapeNotVerified */ echo $html; ?>
                      </div>
                      <?php
                        break;

                      case 'reviews.tab':
                      ?>
                      <div class="reviews">
                          <?php /* @escapeNotVerified */ echo $html; ?>
                      </div>
                      <?php
                        break;
                    }
                ?>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>
