<?php
/**
 * @var $block \AsaanShopping\SearchByLocation\Block\Search
 */
  $baseUrl = $block->getUrl();
  //$categoryProductsJson = $block->getProductCollection();
  $getAddress     =   $block->getAddress();
  //$catUrl       =   $block->getCatUrlByID(4);

  /*echo "<pre>Here:";
  print_r($getAddress);
  echo "</pre>";*/
?>

<div class="search-location header-regular">
  <div class="block block-search search-wrapper size-xl">
    <div class="field search <?php if(!empty($getAddress[1])){echo 'exist';} ?>">
        <div class="control">
          <input type="text" id="locationSearchField" value="<?php if(!empty($getAddress[1])){echo $getAddress[1];} ?>" placeholder="Enter your address to find nearest store..." class="input-text" autocomplete="off">
        </div>
        <div class="actions">
            <span class="action search">
                <span class="icon ic ic-search ib ib-square ib-hover"></span>
            </span>
        </div>
    </div>
  </div>
</div>

<script type="text/javascript">
var baseUrl = "<?php echo $baseUrl; ?>";
var autocomplete;
var selectedLocation = {};
function initAutocomplete()
{
  var defaultBounds = new google.maps.LatLngBounds(
    new google.maps.LatLng(24.738141899609808, 67.08159251411485),
    new google.maps.LatLng(24.78802243953795, 66.97310252388047)
  );
  autocomplete = new google.maps.places.Autocomplete(document.getElementById('locationSearchField'), {
    bounds: defaultBounds,
    strictBounds: true,
    types: ['geocode'],
    componentRestrictions: {country: "pk"}
   });
  autocomplete.addListener('place_changed', fillInAddress);
  initMarkerMapView();
}
function fillInAddress()
{
  selectedLocation = {
    categoryId:4,
    address:'',
    lat:'',
    lng:''
  };
  var place = autocomplete.getPlace();
  selectedLocation.address = String(document.getElementById('locationSearchField').value);
  selectedLocation.lat = place.geometry.location.lat();
  selectedLocation.lng = place.geometry.location.lng();
  onSubmit();
}
function onSubmit()
{
  jQuery.ajax({
      type: 'post',
      showLoader:true,
      url: baseUrl+'searchresultapi/index/searchapi/',
      data: selectedLocation,
      success: function (payload)
      {
        if(payload.status)
        {
          window.location.href = payload.response+"?lat="+selectedLocation.lat+"&lng="+selectedLocation.lng;
        }
      }
  });
}
/*function geolocate()
{
  if (navigator.geolocation)
  {
    navigator.geolocation.getCurrentPosition(function(position)
    {
      var geolocation = {
        lat: position.coords.latitude,
        lng: position.coords.longitude
      };
      var circle = new google.maps.Circle({
        center: geolocation,
        radius: position.coords.accuracy
      });
      autocomplete.setBounds(circle.getBounds());
    });
  }
}*/

function initMarkerMapView()
{
  if(typeof googleMapWithMarkerObj != "undefined" && typeof google != "undefined")
  {
    var map = new google.maps.Map(document.getElementById(googleMapWithMarkerObj.elmId), {
      zoom: 16,
      center: googleMapWithMarkerObj.myLatLng
    });
    var marker = new google.maps.Marker({
      position: googleMapWithMarkerObj.myLatLng,
      map: map,
      title: googleMapWithMarkerObj.title
    });
  }
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCkzuTcqRg86jAPknuUwAmvW0bpzd2TJU0&libraries=places&callback=initAutocomplete" async defer></script>
