<div class="header-regular">
  <div class="block block-search search-wrapper size-xl">
    <div class="field search" style="border-bottom: 4px solid #ffcd18;">
        <div class="control">
          <input type="text" name="q" value="" placeholder="Enter your address to find nearest store..." class="input-text" maxlength="128" role="combobox" aria-haspopup="false" aria-autocomplete="both" autocomplete="off">
        </div>
        <div class="actions">
            <button type="submit" title="Search" class="action search">
                <span class="icon ic ic-search ib ib-square ib-hover" style="color:#ffcd18"></span>
            </button>
        </div>
    </div>
  </div>
</div>
