<div class="search-location header-regular">
  <div class="block block-search search-wrapper size-xl">
    <div class="field search">
        <div class="control">
          <input type="text" id="locationSearchField" value="" placeholder="Enter your address to find nearest store..." class="input-text" autocomplete="off">
        </div>
        <div class="actions">
            <span class="action search">
                <span class="icon ic ic-search ib ib-square ib-hover"></span>
            </span>
        </div>
        <div class="autocomplete-menu hide">
          <table id="locationMenuTable" width="100%"></table>
        </div>
    </div>
  </div>
</div>

<script>
var allLocations = [
  [
    "gulistan-e-jauhor, block 15,",
    "karachi,",
    "pakistan",
    "24.8686617",
    "67.08562600000005"
  ],[
    "gulshan-e-iqbal, block 15,",
    "karachi,",
    "pakistan",
    "24.8686617",
    "67.08562600000005"
  ]
];
require([
  'jquery',
  'Magento_Ui/js/modal/modal',
  'dataTables',
  'domReady!'
], function($, modal, dataTables)
{
  var sTb = $('#locationMenuTable').DataTable({
    "data":allLocations,
    "info":false,
    "columns": [
            { title: "address" },
            { title: "city" },
            { title: "country" },
            { title: "lat" },
            { title: "lng" }
        ],
    "language": {
        "zeroRecords": "No records."
      }
  });

  $("#locationSearchField").blur(function()
  {
    setTimeout(function(){
      $("#locationMenuTable_wrapper").parent().addClass("hide");
    },800);
  });
  $('#locationSearchField').focus(function()
  {
    $("#locationMenuTable_wrapper").parent().removeClass("hide");
    sTb.search($(this).val()).draw();
  });

  $('#locationSearchField').keyup(function()
  {
    sTb.search($(this).val()).draw();
    //sTb.columns(4).search(teamName).draw();
  });

  $('#locationMenuTable').on('click','tbody tr', function(e)
  {
    e.preventDefault();
    var rowData = jQuery.extend(true, [], sTb.row(this).data());
    $("#locationMenuTable_wrapper").parent().addClass("hide");
    rowData.pop();
    rowData.pop();
    rowData = String(rowData).replace(/,,/g, ', ');
    $('#locationSearchField').val(rowData);
  });
});
</script>
